name: Destroy VPC na AWS

on:
  workflow_dispatch  # Permite executar manualmente a destruição da VPC

jobs:
  destroy:
    name: Deletar VPC da AWS com Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Credenciais AWS via Secrets
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Testar Conexão com a AWS
        run: aws sts get-caller-identity

      - name: Instalar Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -o terraform.zip https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar Configuração Terraform
        run: terraform validate

      - name: Executar Terraform Destroy
        run: terraform destroy -auto-approve